# -*- coding: utf-8 -*-
"""JumpShipCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UVoZS6FnoMHjqlySsNU7ZTdAnYyORAr
"""

import streamlit as st

def compare_offers(coypay, coyal, coybonus, coyflexi, nowpay, nowal, nowbonus, nowflexi):
    # Calculate total package for the new company
    coytotal = (coypay * 12) + ((coypay / 160) * coyal) + (coybonus * coypay) + coyflexi

    # Calculate total package for the current job
    nowtotal = (nowpay * 12) + ((nowpay / 160) * nowal) + (nowbonus * nowpay) + nowflexi

    # Calculate the increment percentage
    increment = ((coytotal - nowtotal) / nowtotal) * 100

    # Output suggestions based on the increment
    if increment > 30:
        st.success(f"Increment is {increment:.2f}%. You can strongly consider the new offer.")
    elif increment > 20:
        st.info(f"Increment is {increment:.2f}%. You may want to consider the new offer.")
    elif increment > 10:
        st.warning(f"Increment is {increment:.2f}%. Not really worth considering.")
    else:
        st.error(f"Increment is {increment:.2f}%. Definitely not worth considering.")

# Streamlit UI
st.title("Job Offer Comparison")

st.subheader("Enter details for the new company's offer:")
coypay = st.number_input("New company's basic pay (per month):", min_value=0.0, step=1000.0)
coyal = st.number_input("New company's annual leave days:", min_value=0.0, step=1.0)
coybonus = st.number_input("New company's total months of bonus + AWS:", min_value=0.0, step=0.5)
coyflexi = st.number_input("New company's flexi benefits:", min_value=0.0, step=100.0)

st.subheader("Enter details for your current job:")
nowpay = st.number_input("Current basic pay (per month):", min_value=0.0, step=1000.0)
nowal = st.number_input("Current annual leave days:", min_value=0.0, step=1.0)
nowbonus = st.number_input("Current total months of bonus + AWS:", min_value=0.0, step=0.5)
nowflexi = st.number_input("Current flexi benefits:", min_value=0.0, step=100.0)

# Add a button to trigger the comparison
if st.button("Compare Offers"):
    compare_offers(coypay, coyal, coybonus, coyflexi, nowpay, nowal, nowbonus, nowflexi)