# -*- coding: utf-8 -*-
"""JumpShipCalculator(v1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUoIkBuJnWpc7WSGSohJFT4Fhx2w17X0

Variables:
1. coypay: how much basic pay they offer
2. coyal: how many days of AL they give
3. coybonus: how many months of bonus + aws in total they would give? (take a max)
4. coyflexi: how much flexi they give

5. nowpay: what is your current basic pay
6. nowal: how many days of AL you have
7. nowbonus: how many months of bonus + aws in total would u have? (take a max)
8. nowflexi: how much flexi u have

9. how much total they offer per annum
coytotal = coypay*12 + ((coypay/160)*coyal) + (coybonus*coypay) + coyflexi

10. how much u earn now per annum
nowtotal = nowpay*12 + ((nowpay/160)*nowal) + (nowbonus*nowpay) + nowflexi

11. how much increment in total per year
((coytotal - nowtotal) / nowtotal)*100
"""

def compare_offers(coypay, coyal, coybonus, coyflexi, nowpay, nowal, nowbonus, nowflexi):
    # Calculate total package for the new company
    coytotal = (coypay * 12) + ((coypay / 160) * coyal) + (coybonus * coypay) + coyflexi

    # Calculate total package for the current job
    nowtotal = (nowpay * 12) + ((nowpay / 160) * nowal) + (nowbonus * nowpay) + nowflexi

    # Calculate the increment percentage
    increment = ((coytotal - nowtotal) / nowtotal) * 100

    # Output suggestions based on the increment
    if increment > 30:
        print(f"Increment is {increment:.2f}%. Can highlight consider.")
    elif increment > 20:
        print(f"Increment is {increment:.2f}%. Maybe can consider.")
    elif increment > 10:
        print(f"Increment is {increment:.2f}%. Not worth.")
    else:
        print(f"Increment is {increment:.2f}%. Definitely not worth.")

# Example of usage:
coypay = float(input("Enter the new company's basic pay (per month): "))
coyal = float(input("Enter the new company's annual leave days: "))
coybonus = float(input("Enter the new company's total months of bonus + AWS: "))
coyflexi = float(input("Enter the new company's flexi benefits: "))

nowpay = float(input("Enter your current basic pay (per month): "))
nowal = float(input("Enter your current annual leave days: "))
nowbonus = float(input("Enter your current total months of bonus + AWS: "))
nowflexi = float(input("Enter your current flexi benefits: "))

compare_offers(coypay, coyal, coybonus, coyflexi, nowpay, nowal, nowbonus, nowflexi)